url: http://stevegattuso.me
name: Steve Gattuso
social-image: https://0.gravatar.com/avatar/2c477520c9f03e43ac88b5e0dad2996a?d=https%3A%2F%2Fidenticons.github.com%2F2add55765c2b06325576a98836f22a77.png&r=x&s=460 
highlighter: pygments
include: [".well-known"]
ipv6: false
